
CREATE TABLE roles  (
id INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(50) NOT NULL UNIQUE
);
INSERT INTO roles (nome) VALUES ('user'),('admin');
CREATE TABLE users (
id INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL UNIQUE,
senha VARCHAR(255) NOT NULL, 
registro_data DATETIME DEFAULT CURRENT_TIMESTAMP,
role_id INT,
FOREIGN KEY (role_id) REFERENCES roles(id)
);
CREATE TABLE post (
id INT PRIMARY KEY AUTO_INCREMENT,
title VARCHAR(255) NOT NULL,
text TEXT NOT NULL,
post_date DATETIME DEFAULT CURRENT_TIMESTAMP,
author_id INT,
FOREIGN KEY (author_id) REFERENCES users(id)
);
CREATE TABLE access_control (
id INT PRIMARY KEY AUTO_INCREMENT,
user_id INT,
access_date DATETIME DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (user_id) REFERENCES users(id)
);